src/core/urls.py
"""
Main URL Configuration
"""
from django.contrib import admin
from django.urls import include, path

from core.settings import DEBUG

urlpatterns = [
    path("", include("triage.urls")),
]

if DEBUG:
    urlpatterns += [
        path("admin/", admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

src/triage/urls.py
"""This module URL patterns specific to the Triage Portal."""

from django.urls import path
from graphene_file_upload.django import FileUploadGraphQLView
from triage.api.schema import schema
from triage.views import attachments, cases, filters, findings, home, tool_defect, wiki

urlpatterns = [
    # Cases
    path("cases/<uuid:case_uuid>", cases.show_case),
    path("cases/new", cases.new_case),
    path("cases/save", cases.save_case),
    path("cases/", cases.show_cases),
    # Tooling Defects
    path("tool_defect/<uuid:tool_defect_uuid>", tool_defect.show_tool_defect),
    path("tool_defect/new", tool_defect.show_add_tool_defect),
    path("tool_defect/save", tool_defect.save_tool_defect),
    path("tool_defect/", tool_defect.show_tool_defects),
    # Findings
    path("api/findings/get_files", findings.api_get_files),
    path("api/findings/get_source_code", findings.api_get_source_code),
    path("api/findings/download_file", findings.api_download_file),
    path("api/upload", findings.api_upload_attachment),
    # path("api/findings/get_file_list", findings.api_get_file_list),
    path("api/1/findings/update", findings.api_update_finding),
    # Attachments
    path("attachment/<uuid:attachment_uuid>", attachments.download_attachment),
    path("findings/<uuid:finding_uuid>", findings.show_finding_by_uuid),
    path("findings/upload", findings.show_upload),
    path("findings/", findings.show_findings),
    # Filters
    path("filter/<uuid:filter_uuid>", filters.show_filter),
    path("filter/new", filters.new_filter),
    path("filter/save", filters.save_filter),
    path("filter/execute", filters.execute_filter),
    path("filter/delete", filters.delete_filter),
    path("filter/", filters.show_filters),
    # Wiki
    path("wiki/special:list", wiki.show_wiki_article_list),
    path("wiki/save", wiki.save_wiki_article),
    path("wiki/<str:slug>", wiki.show_wiki_article),
    path(
        "wiki/<str:slug>/<uuid:wiki_article_revision_uuid>",
        wiki.show_wiki_article_revision,
    ),
    path("wiki/<str:slug>/edit", wiki.edit_wiki_article),
    path(
        "wiki/<str:slug>/<uuid:wiki_article_revision_uuid>/edit",
        wiki.edit_wiki_article_revision,
    ),
    path("wiki/", wiki.home),
    # Default (Home)
    path("", home.home),
    # GraphQl Url
    path("graphql", FileUploadGraphQLView.as_view(graphiql=True, schema=schema)),
]

src/triage/models/File.py
from __future__ import annotations

import hashlib
import base64
import logging
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from core import settings
from triage.models import BaseTimestampedModel, BaseUserTrackedModel, WorkItemState

logger = logging.getLogger(__name__)


FILE_TYPES = (
    ("source", _("Source")),
    ("binary", _("Binary")),
    ("other", _("Other")),
    ("unknown", _("Unknown")),
    ("", _("Unknown")),
)


class File(models.Model):
    """
    Represents a file that is associated with an analyzed project.
    """

    class FileType(models.TextChoices):
        SOURCE_CODE = "S", _("Source Code")
        SCAN_RESULT = "R", _("Scan Result")
        UNKNOWN = "U", _("Unknown")

    uuid = models.UUIDField(
        default=uuid.uuid4, editable=False, db_index=True, unique=True
    )
    name = models.CharField(max_length=512, db_index=True)
    path = models.CharField(max_length=4096, db_index=True)
    file_type = models.CharField(
        max_length=16, db_index=True, choices=FileType.choices, default=FileType.UNKNOWN
    )
    content_type = models.CharField(max_length=64, db_index=True, null=True, blank=True)
    file_key = models.CharField(max_length=64, db_index=True, null=True, blank=True)

    def __str__(self):
        return str(self.path)


class FileContent(models.Model):
    """Represents file content."""

    hash = models.BinaryField(max_length=32, db_index=True)
    content_type = models.CharField(max_length=64, db_index=True, null=True, blank=True)
    data = models.BinaryField(null=True, blank=True)

    def __str__(self):
        return base64.b64encode(self.hash).decode("ascii")

    @classmethod
    def generate_hash(cls, data: bytes, encode=False) -> str | bytes:
        """Generates a hash for the given data."""
        digest = hashlib.sha256(data, usedforsecurity=True).digest()
        if encode:
            return base64.b64encode(digest).decode("ascii")
        return digest

src/triage/models/attachment.py
import logging
import uuid

from django.db import models

logger = logging.getLogger(__name__)


class Attachment(models.Model):
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        db_index=True,
        unique=True,
    )
    filename = models.CharField(max_length=1024)
    content = models.BinaryField()
    content_type = models.CharField(max_length=255)

    def __str__(self):
        return self.filename

    def get_absolute_url(self):
        return f"/attachment/{self.uuid}"

src/triage/models/case.py
import logging
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from core import settings
from triage.models import BaseTimestampedModel, BaseUserTrackedModel, WorkItemState

logger = logging.getLogger(__name__)


class Case(BaseTimestampedModel, BaseUserTrackedModel):
    """
    Represents a case that is being reported to a maintainer for a fix.
    """

    class CasePartner(models.TextChoices):
        NONE = "N", _("None")
        GITHUB_SECURITY_LAB = "GS", _("GitHub Security Lab")
        CERT = "CT", _("CERT")
        MSRC = "MS", _("Microsoft Security Response Center")
        NOT_SPECIFIED = "NS", _("Not Specified")

    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        db_index=True,
        unique=True,
    )
    findings = models.ManyToManyField("Finding", related_name="cases")
    state = models.CharField(
        max_length=2,
        choices=WorkItemState.choices,
        default=WorkItemState.NEW,
    )
    title = models.CharField(max_length=1024)
    description = models.TextField(null=True, blank=True)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name="assigned_cases",
        on_delete=models.SET_NULL,
    )
    reported_to = models.CharField(max_length=2048, null=True, blank=True)
    reported_dt = models.DateTimeField(null=True, blank=True)
    reporting_partner = models.CharField(
        max_length=2,
        choices=CasePartner.choices,
        default=CasePartner.NOT_SPECIFIED,
        null=True,
        blank=True,
    )
    reporting_reference = models.CharField(max_length=1024, null=True, blank=True)
    resolved_target_dt = models.DateTimeField(null=True, blank=True)
    resolved_actual_dt = models.DateTimeField(null=True, blank=True)
    notes = models.ManyToManyField("Note", related_name="cases")
    attachments = models.ManyToManyField("Attachment", related_name="cases")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/case/{self.uuid}"

src/triage/models/note.py
import logging

from django.db import models

from triage.models import BaseTimestampedModel, BaseUserTrackedModel

logger = logging.getLogger(__name__)


class Note(BaseTimestampedModel, BaseUserTrackedModel):
    content = models.TextField()

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-created_at"]

src/triage/views/attachments.py
import uuid

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods

from triage.models import Attachment


@login_required
@require_http_methods(["GET"])
def download_attachment(
    request: HttpRequest,
    attachment_uuid: uuid.UUID,
) -> HttpResponse:
    """Downloads an attachment

    Params:
        attachment_uuid: UUID of the attachment to download.
    """
    attachment = get_object_or_404(Attachment, uuid=attachment_uuid)
    return HttpResponse(
        attachment.content,
        content_type=attachment.content_type,
        headers={
            "Content-Disposition": f"attachment; filename={attachment.filename}",
        },
    )

src/triage/views/cases.py
import json
import os
import uuid
from base64 import b64encode
from typing import Any, List
from uuid import UUID

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from triage.models import Case, WorkItemState
from triage.util.general import parse_date
from triage.util.search_parser import parse_query_to_Q
from triage.util.source_viewer import path_to_graph
from triage.util.source_viewer.viewer import SourceViewer


@login_required
@require_http_methods(["GET"])
def show_cases(request: HttpRequest) -> HttpResponse:
    """Shows cases based on a query.

    Params:
        q: query to search for, or all findings if not provided
    """
    query = request.GET.get("q", "").strip()
    cases = Case.objects.all()  # Default
    if query:
        query_object = parse_query_to_Q(Case, query)
        if query_object:
            cases = cases.filter(query_object)

    context = {
        "query": query,
        "cases": cases,
        "case_states": WorkItemState.choices,
        "reporting_partner": Case.CasePartner.choices,
    }

    return render(request, "triage/case_list.html", context)


@login_required
@require_http_methods(["GET"])
def show_case(request: HttpRequest, case_uuid: UUID) -> HttpResponse:
    """Shows a case."""
    case = get_object_or_404(Case, uuid=str(case_uuid))
    context = {
        "case": case,
        "case_states": WorkItemState.choices,
        "reporting_partners": Case.CasePartner.choices,
        "users": get_user_model().objects.all(),
    }
    return render(request, "triage/case_show.html", context)


@login_required
@require_http_methods(["GET"])
def new_case(request: HttpRequest) -> HttpResponse:
    """Shows the new case form."""
    context = {
        "case_states": WorkItemState.choices,
        "reporting_partners": Case.CasePartner.choices,
        "users": get_user_model().objects.all(),
    }
    return render(request, "triage/case_show.html", context)


@login_required
@require_http_methods(["POST"])
def save_case(request: HttpRequest) -> HttpResponse:
    """Saves a case."""
    case_uuid = request.POST.get("case_uuid")
    if not case_uuid:
        case = Case()
        case.created_by = request.user
    else:
        case = get_object_or_404(Case, uuid=case_uuid)

    case.title = request.POST.get("title")
    case.state = request.POST.get("state")
    case.description = request.POST.get("description")

    assigned_to = request.POST.get("assigned_to")
    if assigned_to:
        case.assigned_to = get_user_model().objects.get(username=assigned_to)
    else:
        case.assigned_to = None

    case.reported_to = request.POST.get("reported_to")
    case.reporting_partner = request.POST.get("reporting_partner")
    case.reporting_reference = request.POST.get("reporting_reference")
    case.reported_dt = parse_date(request.POST.get("reported_dt"))
    case.resolved_target_dt = parse_date(request.POST.get("resolved_target_dt"))
    case.resolved_actual_dt = parse_date(request.POST.get("resolved_actual_dt"))
    case.updated_by = request.user

    if not case.created_by:
        case.created_by = request.user

    case.full_clean()
    case.save()

    note_text = request.POST.get("note_text")
    if note_text and note_text.strip():
        case.notes.create(
            content=note_text,
            created_by=request.user,
            updated_by=request.user,
        )

    return HttpResponseRedirect(f"/cases/{case.uuid}")

src/triage/views/filters.py
from uuid import UUID

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods

from triage.models import Filter
from triage.util.general import strtobool
from triage.util.search_parser import parse_query_to_Q


@require_http_methods(["GET"])
def show_filters(request: HttpRequest) -> HttpResponse:
    """Shows filters based on a query.

    Params:
        q: query to search for, or all findings if not provided
    """
    query = request.GET.get("q", "").strip()
    filters = Filter.objects.all()  # Default
    if query:
        query_object = parse_query_to_Q(Filter, query)
        if query_object:
            filters = filters.filter(query_object)
    context = {"query": query, "filters": filters}
    return render(request, "triage/filter_list.html", context)


@require_http_methods(["GET"])
def new_filter(request: HttpRequest) -> HttpResponse:
    """Show a form to create a new filter."""
    return render(request, "triage/filter_show.html")


@require_http_methods(["GET"])
def show_filter(request: HttpRequest, filter_uuid: UUID) -> HttpResponse:
    """Show a filter."""
    if filter_uuid:
        filter = Filter.objects.get(uuid=str(filter_uuid))
        return render(request, "triage/filter_show.html", {"filter": filter})
    else:
        return HttpResponseNotFound()


@login_required
@require_http_methods(["GET"])
def execute_filter(request: HttpRequest) -> JsonResponse:
    """Execute a filter."""
    filter_uuid = request.GET.get("filter_uuid")
    if filter_uuid:
        filter = Filter.objects.get(uuid=str(filter_uuid))
        filter.execute()
        return JsonResponse({"status": "success"})
    else:
        return HttpResponseBadRequest()


@login_required
@require_http_methods(["POST"])
def delete_filter(request: HttpRequest) -> HttpResponse:
    """Delete a filter."""
    filter_uuid = request.POST.get("filter_uuid")
    if filter_uuid:
        filter = get_object_or_404(Filter, uuid=str(filter_uuid))
        filter.delete()
        return HttpResponseRedirect("/filter")
    else:
        return HttpResponseBadRequest()


@login_required
@require_http_methods(["POST"])
def save_filter(request: HttpRequest) -> HttpResponse:
    """Edit a filter."""
    filter_uuid = request.POST.get("filter_uuid")
    if filter_uuid:
        filter = Filter.objects.get(uuid=filter_uuid)
    else:
        filter = Filter()
        filter.created_by = request.user

    filter.title = request.POST.get("title")
    filter.condition = request.POST.get("condition")
    filter.action = request.POST.get("action")
    filter.active = strtobool(request.POST.get("active"), True)
    filter.priority = int(request.POST.get("priority"))
    filter.updated_by = request.user

    try:
        filter.full_clean()
    except ValidationError as e:
        return render(
            request,
            "triage/filter_edit.html",
            {"filter": filter, "error_messages": e.messages},
        )
    filter.save()

    return HttpResponseRedirect(f"/filter/{filter.uuid}")

src/triage/views/home.py
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.utils import timezone

from triage.models import Case, Finding, ToolDefect


@login_required
def home(request: HttpRequest) -> HttpResponse:
    most_recent_finding = Finding.objects.all().order_by("-updated_at")
    finding_last_updated = (
        most_recent_finding.first().created_at if most_recent_finding else None
    )

    most_recent_case = Case.objects.all().order_by("-updated_at")
    case_last_updated = (
        most_recent_case.first().created_at if most_recent_case else None
    )

    my_work = {
        "num_cases": Case.objects.filter(assigned_to=request.user).count(),
        "num_findings": Finding.objects.filter(assigned_to=request.user).count(),
        "num_tool_defects": ToolDefect.objects.filter(assigned_to=request.user).count(),
    }
    metrics = {
        "num_findings": Finding.objects.count(),
        "num_active_findings": Finding.active_findings.count(),
        "num_new_findings": Finding.active_findings.filter(
            created_at__gt=timezone.now() - timedelta(days=7),
        ).count(),
    }
    context = {
        "finding_last_updated": finding_last_updated,
        "case_last_updated": case_last_updated,
        "my_work": my_work,
        "user": request.user,
        "metrics": metrics,
        "last_week": timezone.now() - timedelta(days=7),
    }
    return render(request, "triage/home.html", context)

src/triage/templates/triage/case_list.html
{% extends "./base.html" %}

{% block body %}
<style>

</style>

<div class="row" style="margin-top: 5px">
    <div class="col-12">
        <label for="cases_query" class="visually-hidden">Search Query</label>
        <form action="/cases/" method="get">
            <div class="input-group mb-3">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
                <input type="text" name="q" class="form-control" id="cases_query" placeholder="Search Query..." spellcheck="false" autocomplete="off" value="{{ query }}"/>
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Queries</button>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><h6 class="dropdown-header">Shared Queries</h6></li>
                    <li><a class="dropdown-item" href="/cases?q=">All Cases</a></li>
                    <li><a class="dropdown-item" href="/cases?q=closed,resolved+updated_dt:>=@today-30">Recently Closed</a></li>
                    <li><a class="dropdown-item" href="/cases?q=state:active">Active Cases</a></li>
                    <li><a class="dropdown-item" href="/cases?q=assigned_to:@me">Assigned to Me</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><h6 class="dropdown-header">My Queries</h6></li>
                    <li><a class="dropdown-item" href="/cases?q=assigned_to:@me">Assigned to Me</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Save Current Query As...</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="/wiki/Query_Syntax_Info">Query Syntax Info</a></li>
                </ul>
            </div>
        </form>
    </div>
</div>
<div class="row" style="margin-top: 8px">
    <div class="col-lg-12">
        <h4>Cases</h4>
        {% if cases %}
            <table id="case_list" class="table table-sm table-hover" style="overflow-y:auto">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th class="text-nowrap">Assigned To</th>
                        <th class="text-nowrap">State</th>
                        <th class="text-nowrap">Reporting Partner</th>
                        <th class="text-nowrap">Reported</th>
                        <th class="text-nowrap">Resolution Estimate</th>

                    </tr>
                </thead>
                <tbody style="word-break: break-word;white-space:normal;word-wrap:break-word">
                    {% for case in cases %}
                        <tr class="data_row" data-case_uuid="{{ case.uuid }}" style="cursor:pointer">
                            <td>{{ case.title }}</td>
                            <td>{{ case.assigned_to.get_full_name|default:'<i>Unassigned</i>' }}</td>
                            <td>{{ case.get_state_display }}</td>
                            <td>{{ case.get_reporting_partner_display }}</td>
                            <td>{{ case.reported_dt|date:"SHORT_DATE_FORMAT" }}</td>
                            <td>{{ case.resolved_target_dt|date:"SHORT_DATE_FORMAT" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center"><i>No cases found.</i></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <i>There are no cases available. Try expanding your query.</i>
        {% endif %}
    </div>
</div>
{% endblock body %}

{% block javascript %}
    /* Handle row clicks */
    $('tr.data_row').on('click', (e) => {
        let case_uuid = $(e.target).closest('tr').data('case_uuid')
        if (case_uuid !== undefined) {
            document.location.href = `/cases/${case_uuid}`;
        }
    });
{% endblock %}

src/triage/templates/triage/findings_list.html
{% extends "./base.html" %}

{% block body %}
{% block main %}
<style>
    #resize_wrapper {
        position: absolute;
        top: 8em;
        left: 1em;
        right: 1em;
        bottom: 1em;
    }
</style>

<div class="row mt-4">
    <div class="col-12">
        <label for="finding_query" class="visually-hidden">Search Query</label>
        <form action="/findings" method="get">
            <div class="input-group mb-3">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
                <input type="text" name="q" class="form-control" id="finding_query" placeholder="Search Query..." spellcheck="false" autocomplete="off" value="{{ query }}"/>
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Queries</button>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><h6 class="dropdown-header">Shared Queries</h6></li>
                    <li><a class="dropdown-item" href="/findings?q=status:Untriaged+tag:backdoor">Untriaged Backdoors</a></li>
                    <li><a class="dropdown-item" href="#">Assigned to Me</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><h6 class="dropdown-header">My Queries</h6></li>
                    <li><a class="dropdown-item" href="#">Assigned to Me</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Save Current Query As...</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="/wiki/Query_Syntax_Info">Query Syntax Info</a></li>
                </ul>
                <a href="/findings/upload" class="btn btn-secondary" type="button" aria-expanded="false"><i class="fa fa-plus"></i> Upload</a>
            </div>

        </form>
    </div>
</div>
<div id="resize_wrapperx" class="row mt-4">
    <div class="col-lg-12 ps-4 pe-4">
        <table id="finding_list" class="table table-sm table-hover">
            <thead>
                <tr>
                    <th class="text-nowrap">Package</th>
                    <th class="text-nowrap">Issue</th>
                    <th class="text-nowrap">Filename</th>
                    <th class="text-nowrap">Tool</th>
                    <th class="text-nowrap">Severity</th>
                    <th class="text-nowrap">State</th>
                </tr>
            </thead>
            <tbody style="word-break: break-word;white-space:normal;word-wrap:break-word">
                {% for finding in findings %}
                    <tr data-finding-uuid="{{ finding.uuid }}" data-finding-title="{{ finding.normalized_title }}" data-file-path="{{ finding.file.path}}" data-file-location="{{ finding.file_line }}" style="cursor:pointer">
                        <td>
                            {% include "triage/widgets/project_name_pretty.html" with project=finding.project_version only %}
                        </td>
                        <td>{{ finding.normalized_title|truncatechars:100 }}</td>
                        <td>{{ finding.get_filename_display }}:{{ finding.file_line }}</td>
                        <td>{{ finding.tool.name }}</td>
                        <td>{{ finding.get_severity_display }}</td>
                        <td>{{ finding.get_state_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="col-12 pagination">
        <ul class="pagination mt-2 ms-auto me-auto">
            {% if findings.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{{ params }}&page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">begin</span>
                    </a>
                </li>
            {% endif %}
            {% for i in findings.paginator.page_range %}
                {% if findings.number == i %}
                    <li class="page-item active"><a class="page-link">{{ i }}</a><span class="sr-only">(current)</span></li>
                {% elif i > findings.number|add:'-7' and i < findings.number|add:'7' %}
                    <li class="page-item"><a class="page-link" href="?{{ params }}&page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if findings.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{{ params }}&page={{ findings.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">end</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
    {% endblock main %}
{% endblock body %}

{% block javascript %}
    /* Handle clicks of the "New Tool Finding" button */
    $('#action_new_tooling_bug').on('click', (e) => {
        let finding_uuid = $('#finding_list').data('finding_uuid');
        if (finding_uuid !== undefined) {
            document.location.href = `/tool_defect/new?finding_uuid=${finding_uuid}`;
        }
    });
{% endblock %}

src/triage/templates/triage/findings_upload.html
{% extends "./base.html" %}

{% block body %}
    {% block main %}
<style>
</style>

{% if status == "ok" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="fas fa-check-circle"></i> <strong>Upload successful!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}

{% if status == "error" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="fas fa-exclamation-triangle"></i> Upload was <strong> NOT </strong> successful!
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}

<div class="row">

    <div class="col-md-3"></div>
    <div class="col-md-6 mt-3">
        <h4>Upload Findings</h4>
        <form class="row g-3" action="/findings/upload" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-12">
                You can upload one or more SARIF files, or a file archive containing both SARIF
                files and source code.
            </div>
            <div class="col-12">
                <label for="uploadFiles" class="form-label">Files to Upload</label>
                <input type="file" multiple="true" class="form-control" id="uploadFiles" name="file[]" accept="application/sarif+json, application/zip, application/gzip, application/x-zip, .sarif, .json, .zip, .tar.gz, .tar.xz, .tgz" required="true">
            </div>
            <div class="col-12">
                <label for="packageURL" class="form-label">Package URL (with version)</label>
                <input type="text" class="form-control" id="packageURL" required="true" name="package_url" placeholder="pkg:npm/left-pad@1.3.0">
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
    <div class="col-md-3"></div>
</div>
    {% endblock main %}
{% endblock body %}

src/triage/templates/triage/tool_defect_new.html
{% extends "./base.html" %}

{% block body %}
    {% block main %}
        <div class="mb-3"></div>
        {% include "triage/tool_defect_part_edit.html" %}
    {% endblock main %}
{% endblock body %}

src/triage/templates/triage/wiki_show.html
{% extends "./base.html" %}
{% load wiki %}
{% block body %}
    <form action="/article/save" method="post">
        {% csrf_token %}
        <input type="hidden" name="wiki_article_uuid" value="{{ wiki_article.uuid }}"/>

        <div class="row mt-2">
            <div class="col-12">
                <div class="float-end">
                    <a class="btn btn-sm btn-primary" href="{{ wiki_article.get_absolute_edit_url }}"><i class="far fa-edit me-2"></i>Edit</a>
                    <a class="btn btn-sm btn-secondary" href="/wiki/new"><i class="fas fa-plus me-2"></i>New</a>
                    <a class="btn btn-sm btn-secondary" href="/wiki/special:list"><i class="fas fa-list me-2"></i>View All</a>
                </div>

                <h4 class="border-bottom pb-2">{{ wiki_article.current.title }}</h4>
            </div>

            <div class="col-12">
                {{ wiki_article.current.content|wiki_markdown|safe }}
            </div>
        </div>
    </form>
{% endblock body %}